console.log("**************", "SCORE CARD", "**************");
let name = "Arjun Kumar Gaun";
let school_name = "LPKIC";
let grade = "A";
let section = "A1";
let rollno = "3";
let physics = 80;
let chemisty = 90;
let math = 85;
console.log("*   Student Name - ", name,"  *");
console.log("*   School Name  - ", school_name,"             *");
console.log("*   Grage        - ", grade,"                 *");
console.log("*   Section      - ", section,"                *");
console.log("*   Roll No      - ", rollno,"                 *");
console.log("*             ****", "MARKS", "*****         *");
console.log("*    ","physics","    ","chemisty","    ","math  *");
console.log("*        ",physics,"        ",chemisty,"         ",math," *");
console.log("**************", "**********", "**************");
// console.log("Chemisty in Mark =", chemisty);
// console.log("Mark in Math =", math);