let a=10;
let b=4;
let c=5;
console.log("sum is ",a+b);
console.log("sub is ",a-b);
console.log("mult is ",a*b);
console.log("exponential is ",(a**b)**a);
console.log("div is ",a/b);
console.log("mod is ",a%b);
console.log((a+b)+(a*c)+(a/c)+(a-c)+(b**c)+(c-b)+(b%c));
let x=10;
let y=20;
let z=30;
let v=40;
console.log(typeof(x+y),(x+y));
console.log(typeof(y+z),(y+z));
console.log(typeof(z+v),(z+v));